# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy package files and build configs
COPY package*.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build && npm prune --production

# Default command
CMD ["node", "build/index.js"]
